@HostAddress = http://localhost:5169

### Додати нову гру
POST {{HostAddress}}/api/games
Content-Type: application/json

{
  "title": "Crysis",
  "description": "Українізатор тексту та текстур. Автори: Localize Team.",
  "originalLanguage": "ENG",
  "translationStatus": "Completed"
}

### Отримати список усіх ігор
GET {{HostAddress}}/api/games
Accept: application/json

### Знайти гру по ID
GET {{HostAddress}}/api/games/2
Accept: application/json

### Отримати тільки ігри в процесі
GET {{HostAddress}}/api/games?status=InProgress
Accept: application/json

### Оновити статус гри (PUT)
PUT {{HostAddress}}/api/games/2
Content-Type: application/json

{
  "title": "Persona 5 Royal - UKR",
  "description": "Повний переклад",
  "originalLanguage": "JPN",
  "translationStatus": "Completed",
  "teamId": 1
}

### 1. Створити локалізацію для гри
POST {{HostAddress}}/api/localizations
Content-Type: application/json

{
  "Language": "Ukrainian",
  "GameId": 8
}

### 2. Прив'язати команду до локалізації
# Маршрут: /api/localizations/{locId}/teams/{teamId}
POST {{HostAddress}}/api/localizations/1/teams/2

### Створити команду
POST {{HostAddress}}/api/teams
Content-Type: application/json

{
  "Name": "Localize Team",
  "ContactEmail": ""
}

### Видалити гру (DELETE)
DELETE {{HostAddress}}/api/games/1