@HostAddress = http://localhost:5169

### Додати нову гру
POST {{HostAddress}}/api/games
Content-Type: application/json

{
  "title": "test",
  "description": "testing",
  "originalLanguage": "ENG",
  "translationStatus": "InProgress"
}

### Отримати список усіх ігор
GET {{HostAddress}}/api/games
Accept: application/json

### Знайти гру по ID
GET {{HostAddress}}/api/games/2
Accept: application/json

### Отримати тільки ігри в процесі
GET {{HostAddress}}/api/games?status=InProgress
Accept: application/json

### Оновити статус гри (PUT)
PUT {{HostAddress}}/api/games/1
Content-Type: application/json

{
  "title": "Persona 5 Royal - UKR",
  "description": "Повний переклад",
  "originalLanguage": "JPN",
  "translationStatus": "Completed"
}

### Видалити гру (DELETE)
DELETE {{HostAddress}}/api/games/1