// <auto-generated />
using System;
using LocalizationProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LocalizationProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504204340_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Localization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Localizations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameId = 1,
                            Language = "Ukrainian",
                            Status = "In Progress"
                        },
                        new
                        {
                            Id = 2,
                            GameId = 8,
                            Language = "Ukrainian",
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 3,
                            GameId = 4,
                            Language = "English",
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("LocalizationLocalizationTeam", b =>
                {
                    b.Property<int>("LocalizationsId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamsId")
                        .HasColumnType("integer");

                    b.HasKey("LocalizationsId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("LocalizationLocalizationTeam");

                    b.HasData(
                        new
                        {
                            LocalizationsId = 1,
                            TeamsId = 1
                        },
                        new
                        {
                            LocalizationsId = 2,
                            TeamsId = 2
                        },
                        new
                        {
                            LocalizationsId = 3,
                            TeamsId = 2
                        });
                });

            modelBuilder.Entity("LocalizationProject.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LocalizationTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TranslationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocalizationTeamId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            OriginalLanguage = "JPN",
                            Title = "Persona 5 Royal",
                            TranslationStatus = "In Progress"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            OriginalLanguage = "JPN",
                            Title = "Persona 3 Reload",
                            TranslationStatus = "In Progress"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            OriginalLanguage = "JPN",
                            Title = "Persona 4 Golden",
                            TranslationStatus = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            OriginalLanguage = "ENG",
                            Title = "Dispatch",
                            TranslationStatus = "In Progress"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            OriginalLanguage = "ENG",
                            Title = "DOOM (2016)",
                            TranslationStatus = "Completed"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            OriginalLanguage = "ENG",
                            Title = "Tomb Raider (2013)",
                            TranslationStatus = "Completed"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            OriginalLanguage = "ENG",
                            Title = "Terraria",
                            TranslationStatus = "Completed"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            OriginalLanguage = "ENG",
                            Title = "Bioshock",
                            TranslationStatus = "Completed"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            OriginalLanguage = "ENG",
                            Title = "Far Cry",
                            TranslationStatus = "Completed"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            OriginalLanguage = "ENG",
                            Title = "Hades",
                            TranslationStatus = "Completed"
                        });
                });

            modelBuilder.Entity("LocalizationProject.Models.LocalizationTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactEmail = "info@sbt.ua",
                            Description = "",
                            Name = "SBT Localization"
                        },
                        new
                        {
                            Id = 2,
                            ContactEmail = "contact@localize.org",
                            Description = "",
                            Name = "Localize Team"
                        });
                });

            modelBuilder.Entity("Localization", b =>
                {
                    b.HasOne("LocalizationProject.Models.Game", "Game")
                        .WithMany("Localizations")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("LocalizationLocalizationTeam", b =>
                {
                    b.HasOne("Localization", null)
                        .WithMany()
                        .HasForeignKey("LocalizationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LocalizationProject.Models.LocalizationTeam", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LocalizationProject.Models.Game", b =>
                {
                    b.HasOne("LocalizationProject.Models.LocalizationTeam", null)
                        .WithMany("Games")
                        .HasForeignKey("LocalizationTeamId");
                });

            modelBuilder.Entity("LocalizationProject.Models.Game", b =>
                {
                    b.Navigation("Localizations");
                });

            modelBuilder.Entity("LocalizationProject.Models.LocalizationTeam", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
